variable "ModulesUri" {
  type = "list"
  default = [
                            "https://www.powershellgallery.com/api/v2/package/Az.Accounts/1.6.3",
                            "https://devopsgallerystorage.blob.core.windows.net/packages/xactivedirectory.2.19.0.nupkg",
                            "https://www.powershellgallery.com/api/v2/package/AzureAD/2.0.2.4",
                            "https://www.powershellgallery.com/api/v2/package/SLPSLib/1.0",
                            "https://www.powershellgallery.com/api/v2/package/ImportExcel/6.5.1",
                            "https://www.powershellgallery.com/api/v2/package/Posh-SSH/2.2",
                            "https://www.powershellgallery.com/api/v2/package/Az.Advisor/1.0.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.Aks/1.0.2",
                            "https://www.powershellgallery.com/api/v2/package/Az.AnalysisServices/1.1.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.ApiManagement/1.3.2",
                            "https://www.powershellgallery.com/api/v2/package/Az.ApplicationInsights/1.0.2",
                            "https://www.powershellgallery.com/api/v2/package/Az.Automation/1.3.4",
                            "https://www.powershellgallery.com/api/v2/package/Az.Batch/1.1.2",
                            "https://www.powershellgallery.com/api/v2/package/Az.Billing/1.0.1",                              
                            "https://www.powershellgallery.com/api/v2/package/Az.Cdn/1.3.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.CognitiveServices/1.2.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.Compute/2.7.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.ContainerInstance/1.0.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.ContainerRegistry/1.1.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.DataFactory/1.4.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.DataLakeAnalytics/1.0.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.DataLakeShore/1.2.3",
                            "https://www.powershellgallery.com/api/v2/package/Az.DeploymentManager/1.0.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.DevTestLabs/1.0.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.DNSCdn/1.1.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.Eventgrid/1.2.2",
                            "https://www.powershellgallery.com/api/v2/package/Az.Eventhub/1.4.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.FrontDoor/1.1.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.Hdinsight/2.0.2",
                            "https://www.powershellgallery.com/api/v2/package/Az.HealthcareApis/1.0.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.IotHub/1.3.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.Keyvault/1.3.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.LogicApp/1.3.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.MachineLearning/1.1.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.ManagedServices/1.0.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.MarketplaceOrdering/1.0.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.Media/1.1.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.Monitor/1.4.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.Network/1.15.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.NotificationHubs/1.1.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.OperationalInsights/1.3.3",
                            "https://www.powershellgallery.com/api/v2/package/Az.PolicyInsights/1.1.3",
                            "https://www.powershellgallery.com/api/v2/package/Az.PowerBIEmbedded/1.1.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.RecoveryServices/1.4.5",
                            "https://www.powershellgallery.com/api/v2/package/Az.RedisCache/1.1.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.Relay/1.0.2",
                            "https://www.powershellgallery.com/api/v2/package/Az.Resources/1.7.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.ServiceBus/1.4.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.ServiceFabric/1.2.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.SignalR/1.1.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.Sql/1.15.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.Storage/1.8.0",
                            "https://www.powershellgallery.com/api/v2/package/Az.StorageSync/1.2.1",
                            "https://www.powershellgallery.com/api/v2/package/Az.StreamAnalytics/1.0.0", 
                           "https://www.powershellgallery.com/api/v2/package/Az.TrafficManager/1.0.2",
                           "https://www.powershellgallery.com/api/v2/package/Az.Websites/1.5.0", 
                           "https://www.powershellgallery.com/api/v2/package/Az/2.6.0"
  ]
  }
  variable "ModulesName" {
  type = "list"
  default = [
    "Az.Accounts",
    "xactivedirectory",        
    "AzureAD",                  
    "SLPSLib",                 
    "ImportExcel",              
    "Posh-SSH",                            
    "Az.Advisor",             
    "Az.Aks",                
    "Az.AnalysisServices",  
    "Az.ApiManagement",  
    "Az.ApplicationInsights", 
    "Az.Automation",          
    "Az.Batch",              
    "Az.Billing",                                  
    "Az.Cdn",               
    "Az.CognitiveServices",  
    "Az.Compute", 
    "Az.ContainerInstance", 
    "Az.ContainerRegistry", 
    "Az.DataFactory",   
    "Az.DataLakeAnalytics", 
    "Az.DataLakeStore",   
    "Az.DeploymentManager",
    "Az.DevTestLabs",     
    "Az.Dns",       
    "Az.EventGrid",      
    "Az.EventHub",      
    "Az.FrontDoor",       
    "Az.HDInsight",     
    "Az.HealthcareApis",
    "Az.IotHub",   
    "Az.KeyVault",    
    "Az.LogicApp",
    "Az.MachineLearning", 
    "Az.ManagedServices", 
    "Az.MarketplaceOrdering",
    "Az.Media",          
    "Az.Monitor",   
    "Az.Network",     
    "Az.NotificationHubs",
    "Az.OperationalInsights",
    "Az.PolicyInsights",   
    "Az.PowerBIEmbedded",   
    "Az.RecoveryServices",   
    "Az.RedisCache",      
    "Az.Relay",           
    "Az.Resources",          
    "Az.ServiceBus",     
    "Az.ServiceFabric",  
    "Az.SignalR",         
    "Az.Sql",      
    "Az.Storage",  
    "Az.StorageSync",
    "Az.StreamAnalytics", 
    "Az.TrafficManager",
    "Az.Websites",
    "Az" 
  ]
}

variable resource_group_name {
  default = ""
  description = "Resource group name"
}
variable "AutomationName" {
  description = "Name of the Automation Account"
  default     = "Automation-01"
}
variable "location" {}
variable "Tags" {}
